# Generated by Django 4.2.3 on 2023-08-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_arena', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_product', models.CharField(max_length=200)),
                ('d_description', models.CharField(max_length=300)),
                ('d_price', models.IntegerField()),
                ('d_img', models.ImageField(upload_to='images/')),
                ('d_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_arena.category')),
            ],
        ),
    ]
